# Generated by Django 4.0.6 on 2022-08-14 15:21

import chapter3.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='friend',
            name='name',
            field=models.CharField(max_length=100, validators=[chapter3.models.number_only]),
        ),
    ]
